/**
 * AiTag — small monochrome pill that marks AI-produced content.
 * Uses dashed border and tabular font to signal provenance clearly.
 */
export function AiTag() {
  return (
    <span
      className="inline-flex items-center px-1.5 py-0.5 text-[10px] font-medium tracking-widest
        border border-dashed border-ink-2 text-ink-2 rounded-sm font-mono uppercase select-none"
      aria-label="Generated by AI"
    >
      AI
    </span>
  );
}
