import { sql } from 'drizzle-orm';
import { writeAudit } from '../audit/log';
import { verifyChain } from '../audit/verifier';
import type { DB } from '../db/client';
import { sendEmail } from '../notifications/resend';

export type AlertResult = { ok: true } | { ok: false; reason: string };

export async function runAuditAnchorAlert(db: DB): Promise<AlertResult> {
  // yesterday in UTC
  const yesterday = new Date(Date.now() - 86_400_000).toISOString().slice(0, 10);

  // 1. Check whether an anchor row exists for yesterday
  const anchorRes = await db.execute(sql`
    select 1 from audit_anchor where date = ${yesterday}::date limit 1
  `);
  const anchorRows = (
    Array.isArray(anchorRes) ? anchorRes : ((anchorRes as { rows?: unknown[] }).rows ?? [])
  ) as unknown[];

  let failureReason: string | null = null;

  if (anchorRows.length === 0) {
    failureReason = `anchor row missing for ${yesterday}`;
  } else {
    // 2. Verify chain for yesterday
    const verifyResult = await verifyChain(db, yesterday, yesterday);
    if (!verifyResult.ok) {
      failureReason = `chain verification failed at id ${verifyResult.failedId} for ${yesterday}`;
    }
  }

  if (failureReason === null) {
    return { ok: true };
  }

  // 3. Load HRA + IT admin emails
  const emailRes = await db.execute(sql`
    select distinct u.email
    from staff_role sr
    join staff s on s.id = sr.staff_id
    join "user" u on u.id = s.user_id
    where sr.role in ('hra', 'it_admin')
  `);
  const emailRows = (
    Array.isArray(emailRes) ? emailRes : ((emailRes as { rows?: unknown[] }).rows ?? [])
  ) as Array<{ email: string }>;

  const subject = `URGENT: audit chain verification failed for ${yesterday}`;
  const text = [
    `Audit chain alert — ${yesterday}`,
    '',
    `Reason: ${failureReason}`,
    '',
    'Please investigate the audit log immediately.',
    'This alert was generated by the daily audit anchor alert job (audit.anchor_alert).',
  ].join('\n');
  const html = `<p><strong>Audit chain alert — ${yesterday}</strong></p>
<p>Reason: ${failureReason}</p>
<p>Please investigate the audit log immediately.</p>
<p><em>This alert was generated by the daily audit anchor alert job.</em></p>`;

  let notifiedCount = 0;
  for (const { email } of emailRows) {
    try {
      await sendEmail({ to: email, subject, text, html });
      notifiedCount++;
    } catch {
      // best-effort — continue notifying remaining recipients
    }
  }

  // 4. Write audit event
  await db.transaction(async (tx) => {
    await writeAudit(tx, {
      eventType: 'audit.anchor.alert',
      actorId: null,
      actorRole: 'system',
      targetType: null,
      targetId: null,
      payload: { date: yesterday, reason: failureReason, notifiedCount },
      ip: null,
      ua: null,
    });
  });

  return { ok: false, reason: failureReason };
}
